version: '3.8'

services:
  pathfinding-visualizer:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true